/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaGrafica;

import CapaLogica.Fachada;
import javax.swing.JOptionPane;

/**
 *
 * @author 62512396
 */
public class IngresoAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IngresoAdmin.class.getName());
   Fachada facha = new Fachada();
    /**
     * Creates new form IngresoUsuario
     */
    public IngresoAdmin() {
        initComponents();
    }

 private void limpiar() {
       IDadmin.setText("");
       nombreadmin.setText("");
         contraadmin.setText("");
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IDadmin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        contraadmin = new javax.swing.JTextField();
        btningreso = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nombreadmin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(802, 536));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("David Libre", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Ingreso Usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 200, 365, 50);

        jLabel5.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("ID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 290, 25, 18);

        IDadmin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        IDadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDadminActionPerformed(evt);
            }
        });
        getContentPane().add(IDadmin);
        IDadmin.setBounds(290, 290, 128, 22);

        jLabel7.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Contraseña:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 370, 107, 18);

        contraadmin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contraadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraadminActionPerformed(evt);
            }
        });
        getContentPane().add(contraadmin);
        contraadmin.setBounds(290, 370, 129, 22);

        btningreso.setText("Ingresar");
        btningreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresoActionPerformed(evt);
            }
        });
        getContentPane().add(btningreso);
        btningreso.setBounds(340, 430, 72, 23);

        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnvolver);
        btnvolver.setBounds(250, 430, 72, 23);

        jLabel8.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Nombre:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 330, 77, 18);

        nombreadmin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nombreadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreadminActionPerformed(evt);
            }
        });
        getContentPane().add(nombreadmin);
        nombreadmin.setBounds(290, 330, 128, 22);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\62512396\\Pictures\\Screenshots\\Captura de pantalla 2025-10-21 144438.png")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 680, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDadminActionPerformed

    private void contraadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraadminActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
dispose();
        setVisible(false);
       MenuPrincipal ventana=new MenuPrincipal();
        ventana.setVisible(true);// 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btningresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresoActionPerformed
 dispose();
        setVisible(false);
        CapaGrafica.MenuAdmin ventana=new CapaGrafica.MenuAdmin();
        ventana.setVisible(true);
        // TODO add your handling code here:
                                             
        try {
            String id = IDadmin.getText();
            String nombre= nombreadmin.getText();
            String contraseña = contraadmin.getText();

            if (IDadmin.getText().isEmpty()  || nombreadmin.getText().isEmpty()|| contraadmin.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debe completar todos los campos.");
                return;
            }
            

            boolean valido = facha.iniciarSesion(id, nombre, contraseña);


         }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al iniciar sesión: " + ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btningresoActionPerformed

    private void nombreadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IngresoAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDadmin;
    private javax.swing.JButton btningreso;
    private javax.swing.JButton btnvolver;
    private javax.swing.JTextField contraadmin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombreadmin;
    // End of variables declaration//GEN-END:variables
}
