/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaGrafica;

/**
 *
 * @author Alumno
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnIngreso = new javax.swing.JButton();
        btnLicencias = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(802, 536));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("David Libre", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AUSENTARIO ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 190, 390, 40);

        jLabel1.setFont(new java.awt.Font("David Libre", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(54, 304, 0, 0);

        jLabel3.setFont(new java.awt.Font("David Libre", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1210, 199, 0, 0);

        jLabel4.setFont(new java.awt.Font("David Libre", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1210, 164, 0, 0);

        jLabel5.setFont(new java.awt.Font("David Libre", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Bienvenido a la plataforma de control de inasistencias de ITI");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 310, 693, 18);

        btnIngreso.setBackground(new java.awt.Color(204, 204, 255));
        btnIngreso.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnIngreso.setForeground(new java.awt.Color(0, 0, 102));
        btnIngreso.setText("Ingreso Usuario");
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngreso);
        btnIngreso.setBounds(500, 400, 200, 40);

        btnLicencias.setBackground(new java.awt.Color(204, 204, 255));
        btnLicencias.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnLicencias.setForeground(new java.awt.Color(0, 0, 102));
        btnLicencias.setText("Licencias Activas");
        btnLicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenciasActionPerformed(evt);
            }
        });
        getContentPane().add(btnLicencias);
        btnLicencias.setBounds(140, 400, 220, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\62512396\\Pictures\\Screenshots\\Captura de pantalla 2025-10-21 144438.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 790, 180);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\62512396\\Pictures\\Screenshots\\Captura de pantalla 2025-10-21 144704.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(470, 180, 300, 407);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\62512396\\Pictures\\Screenshots\\Captura de pantalla 2025-10-21 144704.png")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 180, 300, 407);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\62512396\\Pictures\\Screenshots\\Captura de pantalla 2025-10-21 144704.png")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 180, 300, 407);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
dispose();
        setVisible(false);
        IngresoAdmin ventana=new IngresoAdmin();
        ventana.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresoActionPerformed

    private void btnLicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenciasActionPerformed
        dispose();
        setVisible(false);
       LicenciasAct ventana=new LicenciasAct();
        ventana.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnLicenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngreso;
    private javax.swing.JButton btnLicencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
