/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaGrafica;

/**
 *
 * @author 62512396
 */
public class MenuAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdmin.class.getName());

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnRegistroL = new javax.swing.JButton();
        btnRegistroU = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(802, 536));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("David Libre", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Bienvenido Administrador");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 180, 597, 50);

        btnRegistroL.setBackground(new java.awt.Color(204, 204, 255));
        btnRegistroL.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnRegistroL.setForeground(new java.awt.Color(0, 0, 102));
        btnRegistroL.setText("Registrar Licencia");
        btnRegistroL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroLActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroL);
        btnRegistroL.setBounds(110, 290, 193, 28);

        btnRegistroU.setBackground(new java.awt.Color(204, 204, 255));
        btnRegistroU.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnRegistroU.setForeground(new java.awt.Color(0, 0, 102));
        btnRegistroU.setText("Registrar Usuario");
        btnRegistroU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroUActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroU);
        btnRegistroU.setBounds(370, 290, 175, 28);

        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnvolver);
        btnvolver.setBounds(460, 450, 72, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\62512396\\Pictures\\Screenshots\\Captura de pantalla 2025-10-21 144438.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -20, 690, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroLActionPerformed
dispose();
        setVisible(false);
       RegistroLicencia ventana=new RegistroLicencia();
        ventana.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroLActionPerformed

    private void btnRegistroUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroUActionPerformed

dispose();
        setVisible(false);
       RegistroAdmin ventana=new RegistroAdmin();
        ventana.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroUActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
dispose();
        setVisible(false);
       CapaGrafica.IngresoAdmin ventana=new CapaGrafica.IngresoAdmin();
        ventana.setVisible(true);// 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistroL;
    private javax.swing.JButton btnRegistroU;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
